config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:new, :index, :create, :show, :destroy, :edit, :create, :update]
  resources :books, only: [:new, :index, :create, :show, :destroy, :edit, :create, :update]

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
      @books = Book.all
      @book = Book.new
      @user = current_user
    end

    def create
      @books = Book.all #for validates
      @user = current_user #for validates
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "You have created book successfully."
        redirect_to book_path(@book.id)
      else
        render :index
      end
    end

    def show
      @book = Book.find(params[:id])
      @booknew = Book.new
      @user = @book.user
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end

    def edit
      @book = Book.find(params[:id])
      if
        @book.user == current_user
      else
        redirect_to books_path
      end
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully"
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end




    private

    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no-image-150.png", size: "60x60" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
      <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div id="error_explanation">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li>
            <%= message %>
            </li>
          <% end %>
        </ul>
      <% end %>
      </div>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title,  class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
  <% if @book.errors.any? %>
    <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li>
      <%= message %>
      </li>
    <% end %>
    
  <% end %>
  </div>
  <div class="row">
    <%= render "books/list", book:@book, user:@user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </thead>
          <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag (book.user), :profile_image, :fill, 40, 40, fallback: "no-image-150.png", size: "40x40" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td>
            <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container ">
  <div class="row">
    <%= render "books/list", book:@booknew, user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
       <td>
         <%= link_to user_path(@book.user.id) do %>
         <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no-image-150.png", size: "40x40" %><br/>
         <%= @book.user.name %>
         <% end %>
       </td>
       <td>
         <%= link_to book_path(@book.id) do %>
           <%= @book.title %>
         <% end %>
       </td>
       <td>
         <%= @book.body %>
       </td>
       <% if @book.user == current_user %>
        <td>
          <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm  btn-success" %>
        </td>
        <td>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger" %>
        </td>
      <% end %>
      </tr>

      </table>

    </div>
  </div>
</div>