config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:new, :index, :create, :show, :destroy, :edit, :create, :update]
  resources :books, only: [:new, :index, :create, :show, :destroy, :edit, :create, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to " Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light"  %>
                </li>
                <li>
                  <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"><%= flash[:notice] %></p>
            <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto"><!--mx-auto = 中心に配置-->
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>